admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

utilisateurs_utilisateurs:
    resource: "@UtilisateursUtilisateursBundle/Resources/config/routing.yml"
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
