reservation_index:
    path:     /
    defaults: { _controller: "UtilisateursUtilisateursBundle:Reservation:index" }
    methods:  GET

reservation_show:
    path:     /{id}/show
    defaults: { _controller: "UtilisateursUtilisateursBundle:Reservation:show" }
    methods:  GET

reservation_new:
    path:     /new
    defaults: { _controller: "UtilisateursUtilisateursBundle:Reservation:new" }
    methods:  [GET, POST]

reservation_edit:
    path:     /{id}/edit
    defaults: { _controller: "UtilisateursUtilisateursBundle:Reservation:edit" }
    methods:  [GET, POST]

reservation_delete:
    path:     /{id}/delete
    defaults: { _controller: "UtilisateursUtilisateursBundle:Reservation:delete" }
    methods:  DELETE
